import pytest
from lib import part_1, part_2, expand_universe, calculate_shortest_path

TEST_INPUT = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""

TEST_INPUT_EXPANDED = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
"""


def test_part_1():
    assert part_1(TEST_INPUT) == 374


def test_part_2():
    assert part_2(TEST_INPUT) == 1


def test_expand_universe():
    assert expand_universe(TEST_INPUT) == TEST_INPUT_EXPANDED


@pytest.mark.parametrize(
    "x1, y1, x2, y2, expected",
    (
        (4, 0, 9, 10, 15),
        (0, 2, 12, 7, 17),
        (0, 11, 5, 11, 5),
    )
)
def test_calculate_shortest_path(x1, y1, x2, y2, expected):
    assert calculate_shortest_path(x1, y1, x2, y2) == expected
