import pytest
from lib import expand_universe, extract_galaxies, calculate_shortest_path, sum_shortest_paths_in_expanded_universe

TEST_INPUT = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""

TEST_INPUT_EXPANDED = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
"""


@pytest.mark.parametrize(
    "expansion_factor, expected_sum",
    (
        (2, 374),
        (10, 1030),
        (100, 8410),
    )
)
def test_sum_shortest_paths_in_expanded_universe(expansion_factor, expected_sum):
    assert sum_shortest_paths_in_expanded_universe(TEST_INPUT, expansion_factor) == expected_sum


def test_expand_universe():
    assert expand_universe(extract_galaxies(TEST_INPUT)) == extract_galaxies(TEST_INPUT_EXPANDED)


@pytest.mark.parametrize(
    "x1, y1, x2, y2, expected",
    (
        (4, 0, 9, 10, 15),
        (0, 2, 12, 7, 17),
        (0, 11, 5, 11, 5),
    )
)
def test_calculate_shortest_path(x1, y1, x2, y2, expected):
    assert calculate_shortest_path(x1, y1, x2, y2) == expected
